# Generated by Django 3.2.4 on 2021-06-21 08:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rest_api', '0002_testcase_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsuiteitem',
            name='added',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='testsuiteitem',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
