# Generated by Django 3.2.4 on 2021-06-21 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0003_auto_20210621_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=100),
        ),
    ]
